apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-volume-pipeline
  namespace: mylab1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
