apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mybashapp
      app.kubernetes.io/component: mybashapp
      app.kubernetes.io/instance: mybashapp
    name: mybashapp
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: mybashapp:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: /lab8
      git:
        uri: https://github.com/arunprabhur/EX288.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: ubi8-minimal:latest
      type: Docker
    triggers:
    - github:
        secret: FJ_ykLZ0aNlzEKyJNnA_
      type: GitHub
    - generic:
        secret: qwF5udECkK_uJTdVGMne
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mybashapp
      app.kubernetes.io/component: mybashapp
      app.kubernetes.io/instance: mybashapp
    name: mybashapp
  spec:
    replicas: 1
    selector:
      deploymentconfig: mybashapp
    strategy:
      type: Recreate
      recreateParams:
        post:
          failurePolicy: Abort
          execNewPod:
            containerName: mybashapp
            command: ["/opt/project/post-hook.sh"]  
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deploymentconfig: mybashapp
      spec:
        containers:
        - image: mybashapp:latest
          name: mybashapp
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - mybashapp
        from:
          kind: ImageStreamTag
          name: mybashapp:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
kind: List
metadata: {}
